/**
 * AI-PANEL-FA-INLINE-GUIDE
 * این فایل توسط راهنمای فارسی AI Panel مستندسازی شده است.
 * کامنت‌های «راهنما» توضیح می‌دهند دستور یا بلوک بعدی چه نقشی دارد.
 * این توضیحات بخشی از Runtime نیستند و JavaScript آن‌ها را اجرا نمی‌کند.
 */
// راهنما: این دستور فایل/ماژول را از ماژول «jsr:@supabase/functions-js/edge-runtime.d.ts» وارد می‌کند تا در این فایل قابل استفاده باشد.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
// راهنما: این دستور { withSupabase } را از ماژول «npm:@supabase/server@1.4.1» وارد می‌کند تا در این فایل قابل استفاده باشد.
import { withSupabase } from "npm:@supabase/server@1.4.1";

// راهنما: این دستور متغیر/ثابت «corsHeaders» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

// راهنما: این تابع «json» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function json(data: unknown, status = 200) { /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «Response.json(data, { status, headers: corsHeaders })» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return Response.json(data, { status, headers: corsHeaders }); }
// راهنما: این تابع «fromHex» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function fromHex(hex: string) { /* راهنما: این شرط بررسی می‌کند آیا «!/^[0-9a-f]{64}$/i.test(hex)» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if (!/^[0-9a-f]{64}$/i.test(hex)) /* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw new Error("bad_key"); /* راهنما: این دستور متغیر/ثابت «b» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const b=new Uint8Array(hex.length/2); /* راهنما: این حلقه مجموعه‌ای از داده‌ها یا یک بازه را پیمایش می‌کند و منطق داخل بدنه را برای هر مرحله اجرا می‌کند. */ for(let i=0;i<b.length;i++) /* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «b[i]=parseInt(hex.slice(i*2,i*2+2),16)». */ b[i]=parseInt(hex.slice(i*2,i*2+2),16); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «b» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return b; }
// راهنما: این تابع «toBase64» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function toBase64(bytes: Uint8Array) { /* راهنما: این دستور متغیر/ثابت «s» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ let s=""; /* راهنما: این حلقه مجموعه‌ای از داده‌ها یا یک بازه را پیمایش می‌کند و منطق داخل بدنه را برای هر مرحله اجرا می‌کند. */ for(const b of bytes) /* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «s+=String.fromCharCode(b)». */ s+=String.fromCharCode(b); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «btoa(s)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return btoa(s); }
// راهنما: این تابع «toHex» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function toHex(bytes: Uint8Array) { /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join(""); }
// راهنما: این تابع «sha256» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function sha256(v:string){ /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «toHex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder(…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return toHex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))); }
// راهنما: این تابع «encryptToken» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function encryptToken(token:string,keyHex:string){ /* راهنما: این دستور متغیر/ثابت «key» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const key=await crypto.subtle.importKey("raw",fromHex(keyHex),{name:"AES-GCM"},false,["encrypt"]); /* راهنما: این دستور متغیر/ثابت «iv» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const iv=crypto.getRandomValues(new Uint8Array(12)); /* راهنما: این دستور متغیر/ثابت «encrypted» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(token))); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «`v1:${toBase64(iv)}:${toBase64(encrypted)}`» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return `v1:${toBase64(iv)}:${toBase64(encrypted)}`; }
// راهنما: این تابع «randomSecret» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function randomSecret(){ /* راهنما: این دستور متغیر/ثابت «b» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const b=crypto.getRandomValues(new Uint8Array(32)); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «Array.from(b,x=>x.toString(16).padStart(2,"0")).join("")» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return Array.from(b,x=>x.toString(16).padStart(2,"0")).join(""); }
// راهنما: این تابع «validToken» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function validToken(token:string){ /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «token.length>=20 && token.length<=300 && !/\s/.test(token)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return token.length>=20 && token.length<=300 && !/\s/.test(token); }

// راهنما: این تابع «rubikaCall» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function rubikaCall(token:string,method:string,body:Record<string,unknown>={}){
  // راهنما: این دستور متغیر/ثابت «controller» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const controller=new AbortController(); /* راهنما: این دستور متغیر/ثابت «timeout» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const timeout=setTimeout(()=>controller.abort(),12000);
  // راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود.
  try { /* راهنما: این متغیر «r» نتیجه یا Promise یک درخواست شبکه را نگه می‌دارد. */ const r=await fetch(`https://botapi.rubika.ir/v3/${encodeURIComponent(token)}/${method}`,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify(body),signal:controller.signal}); /* راهنما: این دستور متغیر/ثابت «data» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const data=await r.json().catch(()=>({})); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «{httpOk:r.ok,status:r.status,data}» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return {httpOk:r.ok,status:r.status,data}; }
  finally { /* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «clearTimeout(timeout)». */ clearTimeout(timeout); }
}
// راهنما: این تابع «unwrap» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function unwrap(data:any){ /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «data?.data && typeof data.data==="object" ? data.data : data» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return data?.data && typeof data.data==="object" ? data.data : data; }
// راهنما: این تابع «botIdentity» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function botIdentity(raw:any){ /* راهنما: این دستور متغیر/ثابت «x» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const x=unwrap(raw); /* راهنما: این دستور متغیر/ثابت «b» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const b=x?.bot && typeof x.bot==="object" ? x.bot : x; /* راهنما: این شرط بررسی می‌کند آیا «!b || typeof b!=="object"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!b || typeof b!=="object") /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «null» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return null; /* راهنما: این دستور متغیر/ثابت «id» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const id=b.bot_id ?? b.id ?? b.object_guid ?? b.guid; /* راهنما: این دستور متغیر/ثابت «username» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const username=b.username ?? b.bot_username; /* راهنما: این دستور متغیر/ثابت «title» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const title=b.bot_title ?? b.title ?? b.first_name ?? b.name; /* راهنما: این شرط بررسی می‌کند آیا «!id && !username» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!id && !username) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «null» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return null; /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «{ id:String(id ?? username), username:username?String(username):null, titl…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return { id:String(id ?? username), username:username?String(username):null, title:title?String(title):"Rubika Bot", description:b.description?String(b.description):null }; }
// راهنما: این تابع «apiRejected» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function apiRejected(result:any){ /* راهنما: این دستور متغیر/ثابت «status» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const status=String(result?.data?.status ?? result?.data?.status_det ?? "").toUpperCase(); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «!result.httpOk || status==="ERROR" || status==="FAILED"» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return !result.httpOk || status==="ERROR" || status==="FAILED"; }

// راهنما: این تابع «getWorkspace» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function getWorkspace(admin:any,userId:string,email:string){
  // راهنما: این دستور متغیر/ثابت «{error:userError}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {error:userError}=await admin.from("User").upsert({id:userId,email},{onConflict:"id"}); /* راهنما: این شرط بررسی می‌کند آیا «userError» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(userError) /* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw userError;
  // راهنما: این دستور متغیر/ثابت «{data,error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {data,error}=await admin.from("WorkspaceMember").select("workspaceId").eq("userId",userId).limit(1); /* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error) /* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error; /* راهنما: این شرط بررسی می‌کند آیا «data?.[0]?.workspaceId» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(data?.[0]?.workspaceId) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «data[0].workspaceId as string» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return data[0].workspaceId as string;
  // راهنما: این دستور متغیر/ثابت «workspaceId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const workspaceId=`${userId}:workspace`; /* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await admin.from("Workspace").upsert({id:workspaceId,name:"فضای کاری من"},{onConflict:"id…». */ await admin.from("Workspace").upsert({id:workspaceId,name:"فضای کاری من"},{onConflict:"id"}); /* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await admin.from("WorkspaceMember").upsert({id:`${userId}:member`,workspaceId,userId,role…». */ await admin.from("WorkspaceMember").upsert({id:`${userId}:member`,workspaceId,userId,role:"CUSTOMER"},{onConflict:"id"}); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «workspaceId» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return workspaceId;
}
// راهنما: این تابع «ensureDefaultButtons» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function ensureDefaultButtons(admin:any,botId:string){
  // راهنما: این دستور متغیر/ثابت «{count}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {count}=await admin.from("RubikaButton").select("id",{count:"exact",head:true}).eq("botId",botId); /* راهنما: این شرط بررسی می‌کند آیا «(count??0)>0» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if((count??0)>0) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «بدون مقدار» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return;
  // راهنما: این دستور متغیر/ثابت «rows» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const rows=[
    {title:"🛍 محصولات",actionType:"CATALOG",actionValue:"catalog",sortOrder:10},
    {title:"🛒 سبد خرید",actionType:"CART",actionValue:"cart",sortOrder:20},
    {title:"📦 سفارش‌های من",actionType:"ORDERS",actionValue:"orders",sortOrder:30},
    {title:"☎️ پشتیبانی",actionType:"SUPPORT",actionValue:"اطلاعات پشتیبانی هنوز تنظیم نشده است.",sortOrder:40},
  ].map(x=>({id:crypto.randomUUID(),botId,parentId:null,...x}));
  // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {error}=await admin.from("RubikaButton").insert(rows); /* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error) /* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
}

// راهنما: این دستور متغیر/ثابت «authenticated» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const authenticated=withSupabase({auth:"user"},async(request,ctx)=>{
  // راهنما: این شرط بررسی می‌کند آیا «request.method==="GET"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(request.method==="GET") /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:true,service:"rubika-connect",version:1})» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:true,service:"rubika-connect",version:1});
  // راهنما: این شرط بررسی می‌کند آیا «request.method!=="POST"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(request.method!=="POST") /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"Method not allowed"},405)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"Method not allowed"},405);
  // راهنما: این دستور متغیر/ثابت «userId، email» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const userId=ctx.userClaims?.id, email=ctx.userClaims?.email; /* راهنما: این شرط بررسی می‌کند آیا «!userId||!email» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!userId||!email) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"حساب کاربری معتبر نیست."},401)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"حساب کاربری معتبر نیست."},401);
  // راهنما: این دستور متغیر/ثابت «body» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  let body:any; /* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «body=await request.json()». */ body=await request.json()}catch{/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"درخواست معتبر نیست."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"درخواست معتبر نیست."},400)}
  // راهنما: این دستور متغیر/ثابت «token» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const token=typeof body.token==="string"?body.token.trim():""; /* راهنما: این شرط بررسی می‌کند آیا «!validToken(token)» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!validToken(token)) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"فرمت توکن روبیکا معتبر نیست."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"فرمت توکن روبیکا معتبر نیست."},400);
  // راهنما: این دستور متغیر/ثابت «me» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  let me:any; /* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «me=await rubikaCall(token,"getMe")». */ me=await rubikaCall(token,"getMe")}catch{/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"ارتباط با Rubika Bot API برقرار نشد."},502)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"ارتباط با Rubika Bot API برقرار نشد."},502)}
  // راهنما: این دستور متغیر/ثابت «identity» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const identity=botIdentity(me.data); /* راهنما: این شرط بررسی می‌کند آیا «apiRejected(me)||!identity» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(apiRejected(me)||!identity) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"روبیکا این توکن را تأیید نکرد. توکن BotFather را ب…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"روبیکا این توکن را تأیید نکرد. توکن BotFather را بررسی کنید."},401);
  // راهنما: این دستور متغیر/ثابت «admin» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const admin=ctx.supabaseAdmin; /* راهنما: این دستور متغیر/ثابت «workspaceId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ let workspaceId:string; /* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «workspaceId=await getWorkspace(admin,userId,email)». */ workspaceId=await getWorkspace(admin,userId,email)}catch(e){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error(e)». */ console.error(e);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"Workspace آماده نشد."},500)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"Workspace آماده نشد."},500)}
  // راهنما: این دستور متغیر/ثابت «{data:existing}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {data:existing}=await admin.from("RubikaBot").select("id,workspaceId").eq("rubikaBotId",identity.id).maybeSingle(); /* راهنما: این شرط بررسی می‌کند آیا «existing && existing.workspaceId!==workspaceId» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(existing && existing.workspaceId!==workspaceId) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"این ربات قبلاً به حساب دیگری متصل شده است."},409)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"این ربات قبلاً به حساب دیگری متصل شده است."},409);
  // راهنما: این دستور متغیر/ثابت «{data:secret}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {data:secret}=await admin.from("AppSecret").select("value").eq("id","rubika_token_encryption").single(); /* راهنما: این شرط بررسی می‌کند آیا «!secret?.value» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!secret?.value) /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"کلید رمزنگاری روبیکا در دسترس نیست."},500)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"کلید رمزنگاری روبیکا در دسترس نیست."},500);
  // راهنما: این دستور متغیر/ثابت «tokenCiphertext» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const tokenCiphertext=await encryptToken(token,secret.value); /* راهنما: این دستور متغیر/ثابت «webhookSecret» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const webhookSecret=randomSecret(); /* راهنما: این دستور متغیر/ثابت «webhookSecretHash» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const webhookSecretHash=await sha256(webhookSecret);
  // راهنما: این دستور متغیر/ثابت «{data:bot,error:saveError}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const {data:bot,error:saveError}=await admin.from("RubikaBot").upsert({workspaceId,rubikaBotId:identity.id,username:identity.username,displayName:identity.title,description:identity.description,tokenCiphertext,webhookSecretHash,status:"ACTIVE"},{onConflict:"rubikaBotId"}).select("id,rubikaBotId,username,displayName,description,status,welcomeMessage").single();
  // راهنما: این شرط بررسی می‌کند آیا «saveError||!bot» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(saveError||!bot){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error(saveError)». */ console.error(saveError);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"ذخیره ربات روبیکا انجام نشد."},500)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"ذخیره ربات روبیکا انجام نشد."},500)}
  // راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود.
  try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await ensureDefaultButtons(admin,bot.id)». */ await ensureDefaultButtons(admin,bot.id)}catch(e){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error("rubika defaults",e)». */ console.error("rubika defaults",e)}
  // راهنما: این دستور متغیر/ثابت «webhookUrl» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const webhookUrl=`https://spncmjuvnvfkrahjnyjm.supabase.co/functions/v1/rubika-webhook/${encodeURIComponent(identity.id)}/${webhookSecret}`;
  // راهنما: این دستور متغیر/ثابت «endpoint» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  let endpoint:any; /* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «endpoint=await rubikaCall(token,"updateBotEndpoints",{url:webhookUrl,type:"ReceiveUpdate"…». */ endpoint=await rubikaCall(token,"updateBotEndpoints",{url:webhookUrl,type:"ReceiveUpdate"})}catch(e){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error(e)». */ console.error(e);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"ربات ذخیره شد اما Webhook روبیکا فعال نشد."},502)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"ربات ذخیره شد اما Webhook روبیکا فعال نشد."},502)}
  // راهنما: این شرط بررسی می‌کند آیا «apiRejected(endpoint)» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(apiRejected(endpoint)){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error("rubika endpoint rejected",endpoint.data)». */ console.error("rubika endpoint rejected",endpoint.data);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"روبیکا تنظیم Webhook را نپذیرفت."},502)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"روبیکا تنظیم Webhook را نپذیرفت."},502)}
  // راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود.
  try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await rubikaCall(token,"setCommands",{bot_commands:[{command:"start",description:"شروع رب…». */ await rubikaCall(token,"setCommands",{bot_commands:[{command:"start",description:"شروع ربات"},{command:"products",description:"مشاهده محصولات"},{command:"orders",description:"سفارش‌های من"}]})}catch{}
  // راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:true,status:"connected",webhookConfigured:true,bot:{id:bot.id,rub…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد.
  return json({ok:true,status:"connected",webhookConfigured:true,bot:{id:bot.id,rubikaBotId:bot.rubikaBotId,username:bot.username??undefined,displayName:bot.displayName??undefined,description:bot.description??undefined,status:bot.status}});
});

// راهنما: این دستور از نوع ExportAssignment بخشی از کنترل جریان یا تعریف منطق این فایل است.
export default {async fetch(request:Request){ /* راهنما: این شرط بررسی می‌کند آیا «request.method==="OPTIONS"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(request.method==="OPTIONS") /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «new Response("ok",{headers:corsHeaders})» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return new Response("ok",{headers:corsHeaders}); /* راهنما: این دستور متغیر/ثابت «response» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const response=await authenticated(request); /* راهنما: این دستور متغیر/ثابت «headers» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const headers=new Headers(response.headers); /* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «Object.entries(corsHeaders).forEach(([k,v])=>headers.set(k,v))». */ Object.entries(corsHeaders).forEach(([k,v])=>headers.set(k,v)); /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «new Response(response.body,{status:response.status,headers})» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return new Response(response.body,{status:response.status,headers}); }};
