import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server@1.4.1";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"apikey, content-type, x-forwarded-for","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{...corsHeaders,"Cache-Control":"no-store"}});
const validSlug=(v:string)=>/^[a-z0-9][a-z0-9-]{2,63}$/.test(v);
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v);
const validTime=(v:string)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v);

function localToUtc(date:string,time:string,timeZone:string){const[y,m,d]=date.split("-").map(Number);const[h,min]=time.split(":").map(Number);const guess=Date.UTC(y,m-1,d,h,min,0);const f=new Intl.DateTimeFormat("en-US",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});const parts=(value:number)=>{const map=Object.fromEntries(f.formatToParts(new Date(value)).map(p=>[p.type,p.value]));return Date.UTC(Number(map.year),Number(map.month)-1,Number(map.day),Number(map.hour),Number(map.minute),Number(map.second));};let offset=parts(guess)-guess;let result=guess-offset;const adjusted=parts(result)-result;if(adjusted!==offset)result=guess-adjusted;return new Date(result);}
const mins=(v:string)=>{const[h,m]=v.slice(0,5).split(":").map(Number);return h*60+m};
const label=(total:number)=>`${Math.floor(total/60).toString().padStart(2,"0")}:${(total%60).toString().padStart(2,"0")}`;

async function publicContext(admin:any,slug:string){
  const{data:settings,error:settingsError}=await admin.from("BookingSettings").select("workspaceId,timezone,slotIntervalMinutes,minBookingNoticeMinutes,cancellationNoticeMinutes,allowCustomerCancellation,requireDeposit,defaultDepositPercent,publicBookingEnabled,publicSlug").eq("publicSlug",slug).maybeSingle();if(settingsError)throw settingsError;if(!settings?.publicBookingEnabled)return null;
  const[workspace,services,staff,assignments]=await Promise.all([
    admin.from("Workspace").select("id,name").eq("id",settings.workspaceId).maybeSingle(),
    admin.from("BookingService").select("id,title,description,durationMinutes,bufferMinutes,priceAmount,currency,depositPercent,color").eq("workspaceId",settings.workspaceId).eq("isActive",true).order("createdAt",{ascending:true}),
    admin.from("BookingStaff").select("id,name,roleTitle,color").eq("workspaceId",settings.workspaceId).eq("isActive",true).order("createdAt",{ascending:true}),
    admin.from("BookingStaffService").select("staffId,serviceId,priceAmountOverride,durationMinutesOverride,BookingStaff!inner(workspaceId)").eq("BookingStaff.workspaceId",settings.workspaceId),
  ]);const error=[workspace.error,services.error,staff.error,assignments.error].find(Boolean);if(error)throw error;
  return{settings,workspace:workspace.data,services:services.data??[],staff:staff.data??[],assignments:(assignments.data??[]).map((x:any)=>({staffId:x.staffId,serviceId:x.serviceId,priceAmountOverride:x.priceAmountOverride,durationMinutesOverride:x.durationMinutesOverride}))};
}

async function slotsFor(admin:any,ctx:any,date:string,serviceId:string,staffId:string){
  const service=ctx.services.find((x:any)=>x.id===serviceId);const staff=ctx.staff.find((x:any)=>x.id===staffId);const assignment=ctx.assignments.find((x:any)=>x.staffId===staffId&&x.serviceId===serviceId);if(!service||!staff||!assignment||!validDate(date))return[];
  const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const{data:hour,error:hourError}=await admin.from("BookingWorkingHour").select("startTime,endTime,isWorking").eq("staffId",staffId).eq("weekday",weekday).maybeSingle();if(hourError)throw hourError;if(!hour?.isWorking)return[];
  const startTime=hour.startTime.slice(0,5),endTime=hour.endTime.slice(0,5),timezone=ctx.settings.timezone||"Asia/Tehran";const dayStart=localToUtc(date,"00:00",timezone);const next=new Date(dayStart.getTime()+36*3600000);const nextDate=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(next);const dayEnd=localToUtc(nextDate,"00:00",timezone);
  const[appointments,timeOff]=await Promise.all([admin.from("BookingAppointment").select("startsAt,endsAt").eq("workspaceId",ctx.settings.workspaceId).eq("staffId",staffId).in("status",["PENDING","CONFIRMED"]).gte("startsAt",dayStart.toISOString()).lt("startsAt",dayEnd.toISOString()),admin.from("BookingTimeOff").select("startsAt,endsAt").eq("workspaceId",ctx.settings.workspaceId).eq("staffId",staffId).lt("startsAt",dayEnd.toISOString()).gt("endsAt",dayStart.toISOString())]);const error=[appointments.error,timeOff.error].find(Boolean);if(error)throw error;
  const duration=Number(assignment.durationMinutesOverride??service.durationMinutes)+Number(service.bufferMinutes||0);const interval=Math.max(5,Number(ctx.settings.slotIntervalMinutes||15));const nowLimit=Date.now()+Number(ctx.settings.minBookingNoticeMinutes||0)*60000;const start=mins(startTime),end=mins(endTime);const result:any[]=[];
  for(let t=start;t+duration<=end;t+=interval){const time=label(t);const startsAt=localToUtc(date,time,timezone);const endsAt=new Date(startsAt.getTime()+duration*60000);if(startsAt.getTime()<nowLimit)continue;const conflict=[...(appointments.data??[]),...(timeOff.data??[])].some((a:any)=>new Date(a.startsAt).getTime()<endsAt.getTime()&&new Date(a.endsAt).getTime()>startsAt.getTime());if(!conflict)result.push({time,startsAt:startsAt.toISOString()});}
  return result;
}

const handler=withSupabase({auth:"none"},async(request,ctx)=>{
  const admin=ctx.supabaseAdmin;const url=new URL(request.url);
  if(request.method==="GET"){
    const slug=(url.searchParams.get("slug")??"").trim().toLowerCase();if(!validSlug(slug))return json({ok:false,message:"لینک رزرو معتبر نیست."},400);
    try{const info=await publicContext(admin,slug);if(!info)return json({ok:false,message:"صفحه رزرو پیدا نشد یا غیرفعال است."},404);const date=url.searchParams.get("date")??"",serviceId=url.searchParams.get("serviceId")??"",staffId=url.searchParams.get("staffId")??"";const slots=date&&serviceId&&staffId?await slotsFor(admin,info,date,serviceId,staffId):[];const availableStaff=serviceId?info.staff.filter((s:any)=>info.assignments.some((a:any)=>a.staffId===s.id&&a.serviceId===serviceId)):info.staff;const services=info.services.map((s:any)=>({...s}));return json({ok:true,business:{name:info.workspace?.name??"کسب‌وکار",slug},services,staff:availableStaff,staffServices:info.assignments,booking:{timezone:info.settings.timezone,minBookingNoticeMinutes:info.settings.minBookingNoticeMinutes,requireDeposit:info.settings.requireDeposit,defaultDepositPercent:info.settings.defaultDepositPercent},slots});}catch(e){console.error("booking-public-get",e);return json({ok:false,message:"اطلاعات رزرو در دسترس نیست."},500)}
  }
  if(request.method!=="POST")return json({ok:false,message:"Method not allowed"},405);let body:any;try{body=await request.json()}catch{return json({ok:false,message:"درخواست معتبر نیست."},400)}if(body?.website)return json({ok:true,ignored:true},202);
  const slug=typeof body.slug==="string"?body.slug.trim().toLowerCase():"",customerName=typeof body.customerName==="string"?body.customerName.trim().replace(/\s+/g," ").slice(0,140):"",phone=typeof body.phone==="string"?body.phone.trim().replace(/\s+/g,"").slice(0,30):"",serviceId=typeof body.serviceId==="string"?body.serviceId:"",staffId=typeof body.staffId==="string"?body.staffId:"",date=typeof body.date==="string"?body.date:"",time=typeof body.time==="string"?body.time:"",note=typeof body.note==="string"?body.note.trim().slice(0,1000)||null:null;if(!validSlug(slug)||customerName.length<2||!/^\+?[0-9]{8,18}$/.test(phone)||!serviceId||!staffId||!validDate(date)||!validTime(time))return json({ok:false,message:"اطلاعات رزرو ناقص یا نامعتبر است."},400);
  try{const info=await publicContext(admin,slug);if(!info)return json({ok:false,message:"رزرو آنلاین این کسب‌وکار فعال نیست."},404);const service=info.services.find((x:any)=>x.id===serviceId),staff=info.staff.find((x:any)=>x.id===staffId),assignment=info.assignments.find((x:any)=>x.staffId===staffId&&x.serviceId===serviceId);if(!service||!staff||!assignment)return json({ok:false,message:"این خدمت توسط این پرسنل ارائه نمی‌شود."},400);const allowed=await slotsFor(admin,info,date,serviceId,staffId);const selected=allowed.find((x:any)=>x.time===time);if(!selected)return json({ok:false,message:"این ساعت دیگر در دسترس نیست. یک زمان دیگر انتخاب کنید."},409);
    const{data:existing,error:existingError}=await admin.from("BookingCustomer").select("id").eq("workspaceId",info.settings.workspaceId).eq("phone",phone).maybeSingle();if(existingError)throw existingError;if(existing?.id){const oneHourAgo=new Date(Date.now()-3600000).toISOString();const{count,error}=await admin.from("BookingAppointment").select("id",{count:"exact",head:true}).eq("workspaceId",info.settings.workspaceId).eq("customerId",existing.id).eq("source","PUBLIC_BOOKING").gte("createdAt",oneHourAgo);if(error)throw error;if((count??0)>=5)return json({ok:false,message:"تعداد تلاش‌های رزرو زیاد است. کمی بعد دوباره امتحان کنید."},429)}
    const{data:customer,error:customerError}=await admin.from("BookingCustomer").upsert({workspaceId:info.settings.workspaceId,fullName:customerName,phone},{onConflict:"workspaceId,phone"}).select("id").single();if(customerError)throw customerError;const duration=Number(assignment.durationMinutesOverride??service.durationMinutes)+Number(service.bufferMinutes||0),amount=Number(assignment.priceAmountOverride??service.priceAmount);const startsAt=new Date(selected.startsAt),endsAt=new Date(startsAt.getTime()+duration*60000);const depositPercent=service.depositPercent??info.settings.defaultDepositPercent??0,depositAmount=info.settings.requireDeposit?Math.round(amount*Number(depositPercent)/100):0,status=info.settings.requireDeposit?"PENDING":"CONFIRMED";const{data:appointment,error:appointmentError}=await admin.from("BookingAppointment").insert({workspaceId:info.settings.workspaceId,customerId:customer.id,serviceId,staffId,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),status,amount,depositAmount,currency:service.currency??"IRR",source:"PUBLIC_BOOKING",note}).select("id,status,startsAt,amount,depositAmount,currency").single();if(appointmentError?.code==="23P01")return json({ok:false,message:"این ساعت همین الان رزرو شد. زمان دیگری انتخاب کنید."},409);if(appointmentError)throw appointmentError;return json({ok:true,appointment,business:{name:info.workspace?.name??"کسب‌وکار"},service:{title:service.title},staff:{name:staff.name},message:status==="CONFIRMED"?"نوبت با موفقیت ثبت شد.":"نوبت ثبت شد و منتظر تأیید است."},201);
  }catch(e){console.error("booking-public-post",e);return json({ok:false,message:"ثبت نوبت انجام نشد."},500)}
});

export default{async fetch(request:Request){if(request.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});return handler(request)}};
