/**
 * AI-PANEL-FA-INLINE-GUIDE
 * این فایل توسط راهنمای فارسی AI Panel مستندسازی شده است.
 * کامنت‌های «راهنما» توضیح می‌دهند دستور یا بلوک بعدی چه نقشی دارد.
 * این توضیحات بخشی از Runtime نیستند و JavaScript آن‌ها را اجرا نمی‌کند.
 */
// راهنما: این دستور فایل/ماژول را از ماژول «jsr:@supabase/functions-js/edge-runtime.d.ts» وارد می‌کند تا در این فایل قابل استفاده باشد.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
// راهنما: این دستور { withSupabase } را از ماژول «npm:@supabase/server@1.4.1» وارد می‌کند تا در این فایل قابل استفاده باشد.
import { withSupabase } from "npm:@supabase/server@1.4.1";

// راهنما: این دستور متغیر/ثابت «cors» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
// راهنما: این دستور متغیر/ثابت «json» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{...cors,"Cache-Control":"no-store"}});
// راهنما: این دستور متغیر/ثابت «defaults» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const defaults={booking:true,customers:false,finance:false,reports:false,services:false,staff:false,settings:false,automations:false};

// راهنما: این تابع «membership» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function membership(admin:any,userId:string){/* راهنما: این دستور متغیر/ثابت «{data,error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const{data,error}=await admin.from("WorkspaceMember").select("workspaceId,role").eq("userId",userId).limit(1);/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «data?.[0] as {workspaceId:string;role:string}|undefined» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return data?.[0] as {workspaceId:string;role:string}|undefined;}
// راهنما: این تابع «dashboard» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function dashboard(admin:any,workspaceId:string){
  // راهنما: این دستور متغیر/ثابت «[staff,access]» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const [staff,access]=await Promise.all([
    admin.from("BookingStaff").select("id,name,roleTitle,email,phone,color,isActive").eq("workspaceId",workspaceId).order("createdAt",{ascending:true}),
    admin.from("BookingStaffAccess").select("staffId,userId,isEnabled,appointmentScope,permissions,updatedAt").eq("workspaceId",workspaceId),
  ]);/* راهنما: این شرط بررسی می‌کند آیا «staff.error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(staff.error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw staff.error;/* راهنما: این شرط بررسی می‌کند آیا «access.error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(access.error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw access.error;
  // راهنما: این دستور متغیر/ثابت «userIds» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const userIds=(access.data??[]).map((x:any)=>x.userId).filter(Boolean);
  // راهنما: این دستور متغیر/ثابت «users» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  let users:any[]=[];/* راهنما: این شرط بررسی می‌کند آیا «userIds.length» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(userIds.length){/* راهنما: این دستور متغیر/ثابت «{data,error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const{data,error}=await admin.from("User").select("id,email,displayName").in("id",userIds);/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «users=data??[]». */ users=data??[];}
  // راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «{ok:true,staff:(staff.data??[]).map((s:any)=>{const a=(access.data??[]).fi…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد.
  return{ok:true,staff:(staff.data??[]).map((s:any)=>{/* راهنما: این دستور متغیر/ثابت «a» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const a=(access.data??[]).find((x:any)=>x.staffId===s.id);/* راهنما: این دستور متغیر/ثابت «u» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const u=users.find((x:any)=>x.id===a?.userId);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «{...s,access:{userId:a?.userId??null,linkedEmail:u?.email??null,linkedName…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return{...s,access:{userId:a?.userId??null,linkedEmail:u?.email??null,linkedName:u?.displayName??null,isEnabled:a?.isEnabled??false,appointmentScope:a?.appointmentScope??'OWN',permissions:{...defaults,...(a?.permissions??{})},updatedAt:a?.updatedAt??null}}})};
}

// راهنما: این دستور متغیر/ثابت «handler» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const handler=withSupabase({auth:"user"},async(req,ctx)=>{
  // راهنما: این دستور متغیر/ثابت «userId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const userId=ctx.userClaims?.id;/* راهنما: این شرط بررسی می‌کند آیا «!userId» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!userId)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"ورود به حساب الزامی است."},401)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"ورود به حساب الزامی است."},401);
  // راهنما: این دستور متغیر/ثابت «admin» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const admin=ctx.supabaseAdmin;/* راهنما: این دستور متغیر/ثابت «member» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const member=await membership(admin,userId);/* راهنما: این شرط بررسی می‌کند آیا «!member» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!member)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"فضای کاری پیدا نشد."},404)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"فضای کاری پیدا نشد."},404);
  // راهنما: این دستور متغیر/ثابت «isAdmin» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  const isAdmin=member.role==='ADMIN'||member.role==='SUPER_ADMIN';
  // راهنما: این شرط بررسی می‌کند آیا «req.method==='GET'» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(req.method==='GET'){/* راهنما: این شرط بررسی می‌کند آیا «!isAdmin» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!isAdmin)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"مدیریت دسترسی فقط برای مدیر Workspace مجاز است."},…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"مدیریت دسترسی فقط برای مدیر Workspace مجاز است."},403);/* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json(await dashboard(admin,member.workspaceId))» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json(await dashboard(admin,member.workspaceId));}catch(e){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error(e)». */ console.error(e);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"اطلاعات دسترسی پرسنل در دسترس نیست."},500)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"اطلاعات دسترسی پرسنل در دسترس نیست."},500)}}
  // راهنما: این شرط بررسی می‌کند آیا «req.method!=='POST'» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(req.method!=='POST')/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"Method not allowed"},405)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"Method not allowed"},405);
  // راهنما: این شرط بررسی می‌کند آیا «!isAdmin» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(!isAdmin)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"تغییر دسترسی فقط برای مدیر Workspace مجاز است."},4…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"تغییر دسترسی فقط برای مدیر Workspace مجاز است."},403);
  // راهنما: این دستور متغیر/ثابت «body» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
  let body:any;/* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «body=await req.json()». */ body=await req.json()}catch{/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"درخواست معتبر نیست."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"درخواست معتبر نیست."},400)}
  // راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود.
  try{
    // راهنما: این دستور متغیر/ثابت «staffId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
    const staffId=typeof body.staffId==='string'?body.staffId:'';/* راهنما: این دستور متغیر/ثابت «{data:staff,error:se}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const{data:staff,error:se}=await admin.from("BookingStaff").select("id,email").eq("id",staffId).eq("workspaceId",member.workspaceId).maybeSingle();/* راهنما: این شرط بررسی می‌کند آیا «se» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(se)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw se;/* راهنما: این شرط بررسی می‌کند آیا «!staff» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!staff)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"پرسنل پیدا نشد."},404)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"پرسنل پیدا نشد."},404);
    // راهنما: این شرط بررسی می‌کند آیا «body.action==='save_access'» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
    if(body.action==='save_access'){
      // راهنما: این دستور متغیر/ثابت «permissions» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const permissions={...defaults};/* راهنما: این حلقه مجموعه‌ای از داده‌ها یا یک بازه را پیمایش می‌کند و منطق داخل بدنه را برای هر مرحله اجرا می‌کند. */ for(const key of Object.keys(defaults)){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «(permissions as any)[key]=body.permissions?.[key]===true». */ (permissions as any)[key]=body.permissions?.[key]===true;}
      // راهنما: این دستور متغیر/ثابت «appointmentScope» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const appointmentScope=body.appointmentScope==='ALL'?'ALL':'OWN';
      // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const{error}=await admin.from("BookingStaffAccess").upsert({staffId,workspaceId:member.workspaceId,isEnabled:body.isEnabled===true,appointmentScope,permissions},{onConflict:"staffId"});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json(await dashboard(admin,member.workspaceId))» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json(await dashboard(admin,member.workspaceId));
    }
    // راهنما: این شرط بررسی می‌کند آیا «body.action==='link_existing_user'» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
    if(body.action==='link_existing_user'){
      // راهنما: این دستور متغیر/ثابت «email» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const email=(typeof body.email==='string'?body.email:staff.email||'').trim().toLowerCase();/* راهنما: این شرط بررسی می‌کند آیا «!email||!email.includes('@')» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!email||!email.includes('@'))/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"ایمیل معتبر وارد کنید."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"ایمیل معتبر وارد کنید."},400);
      // راهنما: این دستور متغیر/ثابت «{data:user,error:ue}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const{data:user,error:ue}=await admin.from("User").select("id,email,displayName").eq("email",email).maybeSingle();/* راهنما: این شرط بررسی می‌کند آیا «ue» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(ue)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw ue;/* راهنما: این شرط بررسی می‌کند آیا «!user» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!user)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"کاربری با این ایمیل هنوز در AI Panel حساب ندارد."}…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"کاربری با این ایمیل هنوز در AI Panel حساب ندارد."},404);
      // راهنما: این دستور متغیر/ثابت «{data:wm,error:we}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const{data:wm,error:we}=await admin.from("WorkspaceMember").select("id").eq("workspaceId",member.workspaceId).eq("userId",user.id).maybeSingle();/* راهنما: این شرط بررسی می‌کند آیا «we» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(we)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw we;/* راهنما: این شرط بررسی می‌کند آیا «!wm» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!wm)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"این کاربر عضو Workspace نیست. افزودن عضو/دعوت را د…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"این کاربر عضو Workspace نیست. افزودن عضو/دعوت را در مرحله بعد وصل می‌کنیم."},409);
      // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const{error}=await admin.from("BookingStaffAccess").upsert({staffId,workspaceId:member.workspaceId,userId:user.id},{onConflict:"staffId"});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json(await dashboard(admin,member.workspaceId))» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json(await dashboard(admin,member.workspaceId));
    }
    // راهنما: این شرط بررسی می‌کند آیا «body.action==='unlink_user'» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
    if(body.action==='unlink_user'){
      // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
      const{error}=await admin.from("BookingStaffAccess").update({userId:null,isEnabled:false}).eq("staffId",staffId).eq("workspaceId",member.workspaceId);/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json(await dashboard(admin,member.workspaceId))» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json(await dashboard(admin,member.workspaceId));
    }
    // راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"عملیات شناخته‌شده نیست."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد.
    return json({ok:false,message:"عملیات شناخته‌شده نیست."},400);
  }catch(e){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error('booking-staff-access',e)». */ console.error('booking-staff-access',e);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"عملیات دسترسی پرسنل انجام نشد."},500)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"عملیات دسترسی پرسنل انجام نشد."},500)}
});
// راهنما: این دستور از نوع ExportAssignment بخشی از کنترل جریان یا تعریف منطق این فایل است.
export default{async fetch(req:Request){/* راهنما: این شرط بررسی می‌کند آیا «req.method==='OPTIONS'» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(req.method==='OPTIONS')/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «new Response('ok',{headers:cors})» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return new Response('ok',{headers:cors});/* راهنما: این دستور متغیر/ثابت «res» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const res=await handler(req);/* راهنما: این دستور متغیر/ثابت «h» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const h=new Headers(res.headers);/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «Object.entries(cors).forEach(([k,v])=>h.set(k,v))». */ Object.entries(cors).forEach(([k,v])=>h.set(k,v));/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «new Response(res.body,{status:res.status,headers:h})» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return new Response(res.body,{status:res.status,headers:h});}};
