/**
 * AI-PANEL-FA-INLINE-GUIDE
 * این فایل توسط راهنمای فارسی AI Panel مستندسازی شده است.
 * کامنت‌های «راهنما» توضیح می‌دهند دستور یا بلوک بعدی چه نقشی دارد.
 * این توضیحات بخشی از Runtime نیستند و JavaScript آن‌ها را اجرا نمی‌کند.
 */
// راهنما: این دستور { useEffect, useMemo, useState } را از ماژول «react» وارد می‌کند تا در این فایل قابل استفاده باشد.
import { useEffect, useMemo, useState } from 'react';

// راهنما: این Type با نام «Customer» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Customer={id:string;fullName:string;phone:string;isVip:boolean};
// راهنما: این Type با نام «Account» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Account={workspaceId:string;customerId:string;pointsBalance:number;qualifyingPoints:number;tier:'BRONZE'|'SILVER'|'GOLD'|'VIP'};
// راهنما: این Type با نام «Reward» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Reward={id:string;title:string;description?:string|null;pointsCost:number;rewardType:string;rewardValue?:number|null;stock?:number|null;isActive:boolean};
// راهنما: این Type با نام «Redemption» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Redemption={id:string;customerId:string;rewardId:string;pointsSpent:number;code:string;status:'ISSUED'|'USED'|'CANCELLED';issuedAt:string};
// راهنما: این Type با نام «Campaign» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Campaign={id:string;title:string;prize:string;status:'DRAFT'|'OPEN'|'DRAWN'|'CANCELLED';minimumPoints:number;minimumVisits:number;vipOnly:boolean;winnerCustomerId?:string|null;drawnAt?:string|null};
// راهنما: این Type با نام «Entry» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Entry={id:string;campaignId:string;customerId:string};
// راهنما: این Type با نام «Settings» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Settings={enabled:boolean;spendUnitAmount:number|string;pointsPerUnit:number;silverThreshold:number;goldThreshold:number;vipThreshold:number};
// راهنما: این Type با نام «Data» شکل و مقادیر مجاز داده را برای TypeScript مشخص می‌کند و در زمان اجرا کد مستقلی تولید نمی‌کند.
type Data={ok:boolean;message?:string;settings:Settings|null;accounts:Account[];customers:Customer[];rewards:Reward[];redemptions:Redemption[];campaigns:Campaign[];entries:Entry[]};
// راهنما: این دستور متغیر/ثابت «nf» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const nf=new Intl.NumberFormat('fa-IR');
// راهنما: این تابع «api» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function api(body?:unknown){/* راهنما: این متغیر «r» نتیجه یا Promise یک درخواست شبکه را نگه می‌دارد. */ const r=await fetch('/api/booking/loyalty',body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:undefined);/* راهنما: این دستور متغیر/ثابت «d» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const d=await r.json().catch(()=>({})) as Data;/* راهنما: این شرط بررسی می‌کند آیا «!r.ok» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!r.ok)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw new Error(d.message||'عملیات انجام نشد.');/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «d» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return d;}
// راهنما: این تابع «BookingLoyalty» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
export default function BookingLoyalty(){
 // راهنما: این دستور State محلی React برای «[data,setData]، [busy,setBusy]، [error,setError]، [tab,setTab]» می‌سازد تا مقدار آن در UI نگهداری و با تغییرش صفحه دوباره Render شود.
 const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState<'members'|'rewards'|'lottery'>('members');
 // راهنما: این دستور State محلی React برای «[reward,setReward]» می‌سازد تا مقدار آن در UI نگهداری و با تغییرش صفحه دوباره Render شود.
 const[reward,setReward]=useState({title:'',pointsCost:'100',description:'',stock:''});/* راهنما: این دستور State محلی React برای «[campaign,setCampaign]» می‌سازد تا مقدار آن در UI نگهداری و با تغییرش صفحه دوباره Render شود. */ const[campaign,setCampaign]=useState({title:'',prize:'',minimumPoints:'0',minimumVisits:'0',vipOnly:false});
 // راهنما: این useEffect یک اثر جانبی React را اجرا می‌کند؛ معمولاً برای دریافت داده، افزودن Listener یا هماهنگی با سیستم بیرونی استفاده می‌شود.
 useEffect(()=>{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «void api().then(async d=>{if(!d.settings)d=await api({action:'bootstrap'});setData(d)}).c…». */ void api().then(async d=>{/* راهنما: این شرط بررسی می‌کند آیا «!d.settings» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!d.settings)/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «d=await api({action:'bootstrap'})». */ d=await api({action:'bootstrap'});/* راهنما: این دستور با فراخوانی Setter، State مربوط را تغییر می‌دهد تا داده جدید در UI اعمال شود: «setData(d)». */ setData(d)}).catch(e=>setError(e instanceof Error?e.message:'خطا'));},[]);
 // راهنما: این تابع «run» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
 async function run(body:unknown){/* راهنما: این دستور با فراخوانی Setter، State مربوط را تغییر می‌دهد تا داده جدید در UI اعمال شود: «setBusy(true)». */ setBusy(true);/* راهنما: این دستور با فراخوانی Setter، State مربوط را تغییر می‌دهد تا داده جدید در UI اعمال شود: «setError('')». */ setError('');/* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور با فراخوانی Setter، State مربوط را تغییر می‌دهد تا داده جدید در UI اعمال شود: «setData(await api(body))». */ setData(await api(body))}catch(e){/* راهنما: این دستور با فراخوانی Setter، State مربوط را تغییر می‌دهد تا داده جدید در UI اعمال شود: «setError(e instanceof Error?e.message:'خطا')». */ setError(e instanceof Error?e.message:'خطا')}finally{/* راهنما: این دستور با فراخوانی Setter، State مربوط را تغییر می‌دهد تا داده جدید در UI اعمال شود: «setBusy(false)». */ setBusy(false)}}
 // راهنما: این دستور مقدار «customerMap» را با useMemo محاسبه و Cache می‌کند تا محاسبه غیرضروری در Renderهای بعدی تکرار نشود.
 const customerMap=useMemo(()=>new Map((data?.customers||[]).map(c=>[c.id,c])),[data]);
 // راهنما: این دستور متغیر/ثابت «totalPoints» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
 const totalPoints=(data?.accounts||[]).reduce((s,a)=>s+a.pointsBalance,0);/* راهنما: این دستور متغیر/ثابت «vip» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const vip=(data?.accounts||[]).filter(a=>a.tier==='VIP').length;
 // راهنما: این شرط بررسی می‌کند آیا «!data» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
 if(!data)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «<main className="lo load" dir="rtl"><style>{styles}</style>{error||'در حال…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return <main className="lo load" dir="rtl"><style>{styles}</style>{error||'در حال بارگذاری باشگاه مشتریان...'}</main>;
 // راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «<main className="lo" dir="rtl"><style>{styles}</style><header><div><small>…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد.
 return <main className="lo" dir="rtl"><style>{styles}</style><header><div><small>AI PANEL · Loyalty</small><h1>باشگاه مشتریان و قرعه‌کشی</h1><p>امتیازدهی بر اساس پرداخت واقعی، سطح مشتری، پاداش و کمپین قرعه‌کشی.</p></div><div><a href="/app/booking/tools">ابزارها</a><a href="/app/booking/customers">پرونده مشتری</a></div></header>
 {error&&<div className="err">{error}</div>}
 <section className="stats"><article><small>اعضای باشگاه</small><b>{nf.format(data.accounts.length)}</b></article><article><small>امتیاز در گردش</small><b>{nf.format(totalPoints)}</b></article><article><small>اعضای VIP</small><b>{nf.format(vip)}</b></article><article><small>پاداش فعال</small><b>{nf.format(data.rewards.filter(x=>x.isActive).length)}</b></article></section>
 <nav className="tabs"><button className={tab==='members'?'on':''} onClick={()=>setTab('members')}>اعضا و امتیاز</button><button className={tab==='rewards'?'on':''} onClick={()=>setTab('rewards')}>پاداش‌ها</button><button className={tab==='lottery'?'on':''} onClick={()=>setTab('lottery')}>قرعه‌کشی</button></nav>
 {tab==='members'&&<section className="panel"><h2>اعضای باشگاه</h2><div className="members">{data.customers.map(c=>{/* راهنما: این دستور متغیر/ثابت «a» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const a=data.accounts.find(x=>x.customerId===c.id);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «<div key={c.id}><span><b>{c.fullName}</b><small>{c.phone}</small></span><e…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return <div key={c.id}><span><b>{c.fullName}</b><small>{c.phone}</small></span><em className={(a?.tier||'BRONZE').toLowerCase()}>{a?.tier||'BRONZE'}</em><strong>{nf.format(a?.pointsBalance||0)} امتیاز</strong><button disabled={busy} onClick={()=>{/* راهنما: این دستور متغیر/ثابت «p» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const p=Number(prompt('مقدار امتیاز؛ عدد منفی برای کسر امتیاز')||0);/* راهنما: این شرط بررسی می‌کند آیا «p» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(p)/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «void run({action:'adjust_points',customerId:c.id,points:p,reason:'اصلاح دستی از پنل'})». */ void run({action:'adjust_points',customerId:c.id,points:p,reason:'اصلاح دستی از پنل'})}}>± امتیاز</button></div>})}</div></section>}
 {tab==='rewards'&&<><section className="panel form"><h2>پاداش جدید</h2><input placeholder="عنوان پاداش" value={reward.title} onChange={e=>setReward({...reward,title:e.target.value})}/><input type="number" placeholder="هزینه امتیاز" value={reward.pointsCost} onChange={e=>setReward({...reward,pointsCost:e.target.value})}/><input type="number" placeholder="موجودی؛ خالی = نامحدود" value={reward.stock} onChange={e=>setReward({...reward,stock:e.target.value})}/><input placeholder="توضیح" value={reward.description} onChange={e=>setReward({...reward,description:e.target.value})}/><button disabled={busy||!reward.title} onClick={()=>void run({action:'create_reward',...reward,pointsCost:Number(reward.pointsCost),stock:reward.stock===''?null:Number(reward.stock)})}>ثبت پاداش</button></section><section className="panel"><h2>پاداش‌ها</h2><div className="cards">{data.rewards.map(r=><article key={r.id}><span><b>{r.title}</b><small>{r.description||'بدون توضیح'}</small></span><strong>{nf.format(r.pointsCost)} امتیاز</strong><small>{r.stock==null?'موجودی نامحدود':`موجودی ${nf.format(r.stock)}`}</small><button disabled={busy} onClick={()=>void run({action:'toggle_reward',id:r.id,isActive:!r.isActive})}>{r.isActive?'غیرفعال کن':'فعال کن'}</button></article>)}</div></section><section className="panel"><h2>کدهای پاداش صادرشده</h2><div className="members">{data.redemptions.map(x=><div key={x.id}><span><b>{customerMap.get(x.customerId)?.fullName||'مشتری'}</b><small>{x.code}</small></span><em>{x.status}</em><strong>{nf.format(x.pointsSpent)} امتیاز</strong>{x.status==='ISSUED'?<button disabled={busy} onClick={()=>void run({action:'use_redemption',id:x.id})}>مصرف شد</button>:<span/>}</div>)}</div></section></>}
 {tab==='lottery'&&<><section className="panel form"><h2>کمپین قرعه‌کشی جدید</h2><input placeholder="عنوان کمپین" value={campaign.title} onChange={e=>setCampaign({...campaign,title:e.target.value})}/><input placeholder="جایزه" value={campaign.prize} onChange={e=>setCampaign({...campaign,prize:e.target.value})}/><input type="number" placeholder="حداقل امتیاز" value={campaign.minimumPoints} onChange={e=>setCampaign({...campaign,minimumPoints:e.target.value})}/><input type="number" placeholder="حداقل مراجعه" value={campaign.minimumVisits} onChange={e=>setCampaign({...campaign,minimumVisits:e.target.value})}/><label><input type="checkbox" checked={campaign.vipOnly} onChange={e=>setCampaign({...campaign,vipOnly:e.target.checked})}/> فقط VIP</label><button disabled={busy||!campaign.title||!campaign.prize} onClick={()=>void run({action:'create_campaign',...campaign,minimumPoints:Number(campaign.minimumPoints),minimumVisits:Number(campaign.minimumVisits)})}>ساخت کمپین</button></section><section className="panel"><h2>کمپین‌ها</h2><div className="cards">{data.campaigns.map(c=><article key={c.id}><span><b>{c.title}</b><small>{c.prize}</small></span><strong>{nf.format(data.entries.filter(e=>e.campaignId===c.id).length)} شرکت‌کننده</strong><small>حداقل {nf.format(c.minimumPoints)} امتیاز · {nf.format(c.minimumVisits)} مراجعه</small>{c.winnerCustomerId?<p>برنده: <b>{customerMap.get(c.winnerCustomerId)?.fullName||'مشتری'}</b></p>:<div className="actions"><button disabled={busy||c.status!=='OPEN'} onClick={()=>void run({action:'rebuild_campaign',id:c.id})}>بازسازی لیست</button><button disabled={busy||c.status!=='OPEN'} onClick={()=>void run({action:'draw_campaign',id:c.id})}>قرعه‌کشی</button></div>}</article>)}</div></section></>}
 </main>
}
// راهنما: این دستور متغیر/ثابت «styles» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const styles=`*{box-sizing:border-box}.lo{min-height:100vh;background:#f5f7fb;color:#172033;font-family:Inter,Vazirmatn,Tahoma,Arial,sans-serif;padding:26px 24px 100px}.lo>header,.stats,.tabs,.panel,.err{max-width:1250px;margin-left:auto;margin-right:auto}.lo>header{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:16px}.lo header small{font-size:9px;color:#7b58e6;font-weight:900}.lo h1{font-size:27px;margin:5px 0}.lo header p{margin:0;color:#7f8998;font-size:10px}.lo header a{display:inline-block;text-decoration:none;color:#586477;background:#fff;border:1px solid #e1e5ec;border-radius:9px;padding:9px 11px;font-size:9px;margin-right:6px}.err{background:#fff1f2;color:#b83f52;border:1px solid #ffd2d8;padding:10px;border-radius:10px;margin-bottom:10px;font-size:9px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stats article,.panel{background:#fff;border:1px solid #e3e7ee;border-radius:15px;padding:15px}.stats article{display:flex;flex-direction:column}.stats small{font-size:8px;color:#8792a2}.stats b{font-size:18px;margin-top:8px}.tabs{display:flex;gap:6px;margin-top:10px;margin-bottom:10px}.tabs button,.panel button{border:0;border-radius:9px;padding:9px 12px;font-size:9px;font-weight:800;cursor:pointer}.tabs button{background:#e8ebf2;color:#657086}.tabs button.on,.panel button{background:#6757df;color:#fff}.panel{margin-bottom:10px}.panel h2{font-size:12px;margin:0 0 12px}.members>div{display:grid;grid-template-columns:1fr 90px 130px 80px;gap:10px;align-items:center;padding:10px 0;border-top:1px solid #eef1f5}.members span{display:flex;flex-direction:column}.members b{font-size:9px}.members small{font-size:8px;color:#8c96a5;margin-top:3px}.members strong{font-size:9px}.members em{font-style:normal;font-size:8px;font-weight:900}.bronze{color:#9d6b3e}.silver{color:#7d8794}.gold{color:#b88a12}.vip{color:#6d45d9}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.form h2{grid-column:1/-1}.form input{border:1px solid #e0e5ec;border-radius:9px;padding:9px;font-size:9px}.form label{font-size:9px;display:flex;align-items:center;gap:6px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.cards article{border:1px solid #e8ebf1;border-radius:12px;padding:12px;background:#fafbfc;display:flex;flex-direction:column;gap:8px}.cards span{display:flex;flex-direction:column}.cards b{font-size:10px}.cards small,.cards p{font-size:8px;color:#8792a2;margin:0}.cards strong{font-size:11px}.actions{display:flex;gap:6px}.actions button{flex:1}.load{display:grid;place-items:center;font-size:10px}@media(max-width:850px){.lo{padding:16px 10px 100px}.lo>header{display:block}.lo header>div:last-child{margin-top:10px}.stats{grid-template-columns:1fr 1fr}.form{grid-template-columns:1fr 1fr}.cards{grid-template-columns:1fr}.members>div{grid-template-columns:1fr auto}.members>div>*:nth-child(n+3){grid-column:auto}.lo h1{font-size:22px}}`;
