import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server@1.4.1";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(d:unknown,s=200)=>Response.json(d,{status:s,headers:cors});
async function workspace(admin:any,userId:string){const {data,error}=await admin.from("WorkspaceMember").select("workspaceId,role").eq("userId",userId).limit(1);if(error||!data?.[0])return null;return data[0] as {workspaceId:string;role:string};}
const handler=withSupabase({auth:"user"},async(req,ctx)=>{const userId=ctx.userClaims?.id;if(!userId)return json({ok:false,message:"ورود الزامی است."},401);const admin=ctx.supabaseAdmin;const member=await workspace(admin,userId);if(!member)return json({ok:false,message:"Workspace پیدا نشد."},404);const wid=member.workspaceId;
 if(req.method==="GET"){const [siteR,msgR,svcR,staffR]=await Promise.all([admin.from("BookingBusinessSite").select("*").eq("workspaceId",wid).maybeSingle(),admin.from("BookingInboxMessage").select("*").eq("workspaceId",wid).order("createdAt",{ascending:false}).limit(200),admin.from("BookingService").select("id,title,description,durationMinutes,priceAmount,currency,color,isActive").eq("workspaceId",wid).eq("isActive",true),admin.from("BookingStaff").select("id,name,roleTitle,color,isActive").eq("workspaceId",wid).eq("isActive",true)]);const err=[siteR,msgR,svcR,staffR].map((x:any)=>x.error).find(Boolean);if(err)return json({ok:false,message:"دریافت اطلاعات سایت انجام نشد."},500);return json({ok:true,site:siteR.data,messages:msgR.data||[],services:svcR.data||[],staff:staffR.data||[]});}
 if(req.method!=="POST")return json({ok:false,message:"Method not allowed"},405);const body=await req.json().catch(()=>({}));const action=String(body.action||"");
 if(action==="save_site"){if(!["ADMIN","SUPER_ADMIN"].includes(member.role))return json({ok:false,message:"دسترسی مدیر لازم است."},403);const current=(await admin.from("BookingBusinessSite").select("slug").eq("workspaceId",wid).maybeSingle()).data;const slug=String(body.slug||current?.slug||"").trim().toLowerCase();if(!/^[a-z0-9][a-z0-9-]{2,63}$/.test(slug))return json({ok:false,message:"Slug معتبر نیست."},400);const payload={workspaceId:wid,slug,enabled:body.enabled!==false,brandName:String(body.brandName||"کسب‌وکار من").slice(0,120),tagline:String(body.tagline||"").slice(0,220)||null,aboutText:String(body.aboutText||"").slice(0,3000)||null,phone:String(body.phone||"").slice(0,40)||null,email:String(body.email||"").slice(0,160)||null,address:String(body.address||"").slice(0,500)||null,instagramUrl:String(body.instagramUrl||"").slice(0,500)||null,whatsappUrl:String(body.whatsappUrl||"").slice(0,500)||null,websiteUrl:String(body.websiteUrl||"").slice(0,500)||null,logoUrl:String(body.logoUrl||"").slice(0,1000)||null,coverUrl:String(body.coverUrl||"").slice(0,1000)||null,accentColor:/^#[0-9a-fA-F]{6}$/.test(String(body.accentColor||""))?String(body.accentColor):"#6659e5",theme:body.theme==="DARK"?"DARK":"LIGHT",showServices:body.showServices!==false,showStaff:body.showStaff!==false,showBooking:body.showBooking!==false,showContact:body.showContact!==false,showLoyalty:body.showLoyalty!==false,metaTitle:String(body.metaTitle||"").slice(0,160)||null,metaDescription:String(body.metaDescription||"").slice(0,320)||null,updatedAt:new Date().toISOString()};const {error}=await admin.from("BookingBusinessSite").upsert(payload,{onConflict:"workspaceId"});if(error){console.error(error);return json({ok:false,message:error.code==="23505"?"این آدرس سایت قبلاً استفاده شده است.":"ذخیره سایت انجام نشد."},409)}return json({ok:true});}
 if(action==="update_message"){const id=String(body.id||"");const status=String(body.status||"");if(!["NEW","OPEN","DONE","ARCHIVED","SPAM"].includes(status))return json({ok:false,message:"وضعیت نامعتبر است."},400);const patch:any={status,updatedAt:new Date().toISOString()};if(status==="DONE"){patch.handledByUserId=userId;patch.handledAt=new Date().toISOString();}const {error}=await admin.from("BookingInboxMessage").update(patch).eq("id",id).eq("workspaceId",wid);if(error)return json({ok:false,message:"به‌روزرسانی پیام انجام نشد."},500);return json({ok:true});}
 return json({ok:false,message:"Action not found"},404);
});
export default{async fetch(req:Request){if(req.method==="OPTIONS")return new Response("ok",{headers:cors});return handler(req);}};
