/**
 * AI-PANEL-FA-INLINE-GUIDE
 * این فایل توسط راهنمای فارسی AI Panel مستندسازی شده است.
 * کامنت‌های «راهنما» توضیح می‌دهند دستور یا بلوک بعدی چه نقشی دارد.
 * این توضیحات بخشی از Runtime نیستند و JavaScript آن‌ها را اجرا نمی‌کند.
 */
// راهنما: این دستور فایل/ماژول را از ماژول «jsr:@supabase/functions-js/edge-runtime.d.ts» وارد می‌کند تا در این فایل قابل استفاده باشد.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
// راهنما: این دستور { withSupabase } را از ماژول «npm:@supabase/server@1.4.1» وارد می‌کند تا در این فایل قابل استفاده باشد.
import { withSupabase } from "npm:@supabase/server@1.4.1";

// راهنما: این دستور متغیر/ثابت «corsHeaders» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
// راهنما: این تابع «json» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
function json(data:unknown,status=200){/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «Response.json(data,{status,headers:{...corsHeaders,"Cache-Control":"no-sto…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return Response.json(data,{status,headers:{...corsHeaders,"Cache-Control":"no-store"}})}
// راهنما: این تابع «context» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function context(admin:any,userId:string){/* راهنما: این دستور متغیر/ثابت «{data:member,error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const {data:member,error}=await admin.from("WorkspaceMember").select("workspaceId,role").eq("userId",userId).limit(1).maybeSingle();/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این شرط بررسی می‌کند آیا «!member» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!member)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «null» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return null;/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «member» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return member;}
// راهنما: این تابع «snapshot» یک بخش مستقل از منطق برنامه را تعریف می‌کند؛ ورودی‌ها را می‌گیرد و منطق داخل بدنه را اجرا می‌کند.
async function snapshot(admin:any,workspaceId:string){
 // راهنما: این دستور متغیر/ثابت «[settings,accounts,rewards,redemptions,campa…» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
 const [settings,accounts,rewards,redemptions,campaigns,entries,customers,ledger]=await Promise.all([
  admin.from("BookingLoyaltySettings").select("*").eq("workspaceId",workspaceId).maybeSingle(),
  admin.from("BookingLoyaltyAccount").select("*").eq("workspaceId",workspaceId).order("pointsBalance",{ascending:false}).limit(250),
  admin.from("BookingLoyaltyReward").select("*").eq("workspaceId",workspaceId).order("createdAt",{ascending:false}),
  admin.from("BookingLoyaltyRedemption").select("*").eq("workspaceId",workspaceId).order("issuedAt",{ascending:false}).limit(200),
  admin.from("BookingLotteryCampaign").select("*").eq("workspaceId",workspaceId).order("createdAt",{ascending:false}),
  admin.from("BookingLotteryEntry").select("*").eq("workspaceId",workspaceId),
  admin.from("BookingCustomer").select("id,fullName,phone,isVip").eq("workspaceId",workspaceId).order("createdAt",{ascending:false}),
  admin.from("BookingLoyaltyLedger").select("id,customerId,type,deltaPoints,reason,createdAt").eq("workspaceId",workspaceId).order("createdAt",{ascending:false}).limit(200),
 ]);
 // راهنما: این دستور متغیر/ثابت «err» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
 const err=[settings,accounts,rewards,redemptions,campaigns,entries,customers,ledger].map(x=>x.error).find(Boolean);/* راهنما: این شرط بررسی می‌کند آیا «err» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(err)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw err;
 // راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «{ok:true,settings:settings.data,accounts:accounts.data??[],rewards:rewards…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد.
 return {ok:true,settings:settings.data,accounts:accounts.data??[],rewards:rewards.data??[],redemptions:redemptions.data??[],campaigns:campaigns.data??[],entries:entries.data??[],customers:customers.data??[],ledger:ledger.data??[]};
}
// راهنما: این دستور متغیر/ثابت «handler» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
const handler=withSupabase({auth:"user"},async(request,ctx)=>{
 // راهنما: این دستور متغیر/ثابت «userId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
 const userId=ctx.userClaims?.id;/* راهنما: این شرط بررسی می‌کند آیا «!userId» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!userId)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"ورود الزامی است."},401)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"ورود الزامی است."},401);/* راهنما: این دستور متغیر/ثابت «admin» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const admin=ctx.supabaseAdmin;/* راهنما: این دستور متغیر/ثابت «member» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const member=await context(admin,userId);/* راهنما: این شرط بررسی می‌کند آیا «!member» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!member)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"Workspace پیدا نشد."},404)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"Workspace پیدا نشد."},404);/* راهنما: این دستور متغیر/ثابت «workspaceId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const workspaceId=member.workspaceId;
 // راهنما: این شرط بررسی می‌کند آیا «request.method==="GET"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
 if(request.method==="GET")/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json(await snapshot(admin,workspaceId))» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json(await snapshot(admin,workspaceId));
 // راهنما: این شرط بررسی می‌کند آیا «request.method!=="POST"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
 if(request.method!=="POST")/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"Method not allowed"},405)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"Method not allowed"},405);
 // راهنما: این دستور متغیر/ثابت «body» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
 let body:any;/* راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود. */ try{/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «body=await request.json()». */ body=await request.json()}catch{/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"درخواست نامعتبر است."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"درخواست نامعتبر است."},400)}/* راهنما: این دستور متغیر/ثابت «action» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const action=body?.action;
 // راهنما: این بلوک عملیات دارای احتمال خطا را اجرا می‌کند؛ اگر خطایی رخ دهد بخش catch می‌تواند آن را مدیریت کند و finally در صورت وجود همیشه اجرا می‌شود.
 try{
  // راهنما: این شرط بررسی می‌کند آیا «action==="bootstrap"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود.
  if(action==="bootstrap"){
   // راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await admin.from("BookingLoyaltySettings").upsert({workspaceId},{onConflict:"workspaceId"…».
   await admin.from("BookingLoyaltySettings").upsert({workspaceId},{onConflict:"workspaceId"});
   // راهنما: این حلقه مجموعه‌ای از داده‌ها یا یک بازه را پیمایش می‌کند و منطق داخل بدنه را برای هر مرحله اجرا می‌کند.
   for(const c of (await admin.from("BookingCustomer").select("id").eq("workspaceId",workspaceId)).data??[]){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await admin.rpc("booking_loyalty_rebuild_entries",{p_workspace_id:workspaceId,p_campaign_…». */ await admin.rpc("booking_loyalty_rebuild_entries",{p_workspace_id:workspaceId,p_campaign_id:"__noop__"}).catch(()=>undefined);/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «await admin.from("BookingLoyaltyAccount").upsert({workspaceId,customerId:c.id},{onConflic…». */ await admin.from("BookingLoyaltyAccount").upsert({workspaceId,customerId:c.id},{onConflict:"workspaceId,customerId"});}
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="save_settings"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="save_settings"){
   // راهنما: این دستور متغیر/ثابت «spend» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const spend=Math.max(1,Math.round(Number(body.spendUnitAmount||100000)));/* راهنما: این دستور متغیر/ثابت «ppu» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const ppu=Math.max(1,Math.round(Number(body.pointsPerUnit||1)));/* راهنما: این دستور متغیر/ثابت «s» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const s=Math.max(0,Math.round(Number(body.silverThreshold||0)));/* راهنما: این دستور متغیر/ثابت «g» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const g=Math.max(s,Math.round(Number(body.goldThreshold||s)));/* راهنما: این دستور متغیر/ثابت «v» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const v=Math.max(g,Math.round(Number(body.vipThreshold||g)));
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.from("BookingLoyaltySettings").upsert({workspaceId,enabled:body.enabled!==false,spendUnitAmount:spend,pointsPerUnit:ppu,silverThreshold:s,goldThreshold:g,vipThreshold:v,updatedAt:new Date().toISOString()},{onConflict:"workspaceId"});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="adjust_points"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="adjust_points"){
   // راهنما: این دستور متغیر/ثابت «customerId» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const customerId=String(body.customerId||"");/* راهنما: این دستور متغیر/ثابت «points» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const points=Math.trunc(Number(body.points||0));/* راهنما: این شرط بررسی می‌کند آیا «!customerId||!points» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!customerId||!points)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"مشتری و مقدار امتیاز الزامی است."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"مشتری و مقدار امتیاز الزامی است."},400);/* راهنما: این دستور متغیر/ثابت «{data:c}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const {data:c}=await admin.from("BookingCustomer").select("id").eq("id",customerId).eq("workspaceId",workspaceId).maybeSingle();/* راهنما: این شرط بررسی می‌کند آیا «!c» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!c)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"مشتری معتبر نیست."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"مشتری معتبر نیست."},400);/* راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const {error}=await admin.from("BookingLoyaltyLedger").insert({workspaceId,customerId,type:points>0?"BONUS":"ADJUST",deltaPoints:points,reason:String(body.reason||"اصلاح دستی امتیاز").slice(0,300),createdByUserId:userId});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="create_reward"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="create_reward"){
   // راهنما: این دستور متغیر/ثابت «title» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const title=String(body.title||"").trim().slice(0,120);/* راهنما: این دستور متغیر/ثابت «pointsCost» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const pointsCost=Math.max(1,Math.round(Number(body.pointsCost||0)));/* راهنما: این شرط بررسی می‌کند آیا «!title» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!title)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"عنوان پاداش الزامی است."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"عنوان پاداش الزامی است."},400);/* راهنما: این دستور متغیر/ثابت «payload» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const payload={workspaceId,title,description:String(body.description||"").trim().slice(0,500)||null,pointsCost,rewardType:["DISCOUNT_AMOUNT","DISCOUNT_PERCENT","FREE_SERVICE","CUSTOM"].includes(body.rewardType)?body.rewardType:"CUSTOM",rewardValue:body.rewardValue==null||body.rewardValue===""?null:Math.max(0,Math.round(Number(body.rewardValue))),serviceId:body.serviceId||null,stock:body.stock==null||body.stock===""?null:Math.max(0,Math.round(Number(body.stock))),isActive:true};/* راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const {error}=await admin.from("BookingLoyaltyReward").insert(payload);/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="toggle_reward"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="toggle_reward"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.from("BookingLoyaltyReward").update({isActive:!!body.isActive,updatedAt:new Date().toISOString()}).eq("id",body.id).eq("workspaceId",workspaceId);/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="redeem_reward"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="redeem_reward"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.rpc("booking_loyalty_redeem_reward",{p_workspace_id:workspaceId,p_customer_id:String(body.customerId||""),p_reward_id:String(body.rewardId||""),p_user_id:userId});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="cancel_redemption"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="cancel_redemption"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.rpc("booking_loyalty_cancel_redemption",{p_workspace_id:workspaceId,p_redemption_id:String(body.id||""),p_user_id:userId});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="use_redemption"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="use_redemption"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.from("BookingLoyaltyRedemption").update({status:"USED",usedAt:new Date().toISOString()}).eq("id",body.id).eq("workspaceId",workspaceId).eq("status","ISSUED");/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="create_campaign"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="create_campaign"){
   // راهنما: این دستور متغیر/ثابت «title، prize» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const title=String(body.title||"").trim().slice(0,120),prize=String(body.prize||"").trim().slice(0,240);/* راهنما: این شرط بررسی می‌کند آیا «!title||!prize» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(!title||!prize)/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"عنوان و جایزه الزامی است."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"عنوان و جایزه الزامی است."},400);/* راهنما: این دستور متغیر/ثابت «{data:campaign,error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const {data:campaign,error}=await admin.from("BookingLotteryCampaign").insert({workspaceId,title,prize,status:"OPEN",minimumPoints:Math.max(0,Math.round(Number(body.minimumPoints||0))),minimumVisits:Math.max(0,Math.round(Number(body.minimumVisits||0))),vipOnly:!!body.vipOnly,startsAt:body.startsAt||new Date().toISOString(),endsAt:body.endsAt||null,createdByUserId:userId}).select("id").single();/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;/* راهنما: این دستور متغیر/ثابت «rebuilt» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد. */ const rebuilt=await admin.rpc("booking_lottery_rebuild_entries",{p_workspace_id:workspaceId,p_campaign_id:campaign.id});/* راهنما: این شرط بررسی می‌کند آیا «rebuilt.error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(rebuilt.error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw rebuilt.error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="rebuild_campaign"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="rebuild_campaign"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.rpc("booking_lottery_rebuild_entries",{p_workspace_id:workspaceId,p_campaign_id:String(body.id||"")});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="draw_campaign"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="draw_campaign"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.rpc("booking_lottery_draw",{p_workspace_id:workspaceId,p_campaign_id:String(body.id||""),p_user_id:userId});/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این شرط بررسی می‌کند آیا «action==="cancel_campaign"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(action==="cancel_campaign"){
   // راهنما: این دستور متغیر/ثابت «{error}» را تعریف می‌کند و مقدار موردنیاز این بخش از برنامه را نگه می‌دارد.
   const {error}=await admin.from("BookingLotteryCampaign").update({status:"CANCELLED",updatedAt:new Date().toISOString()}).eq("id",body.id).eq("workspaceId",workspaceId).in("status",["DRAFT","OPEN"]);/* راهنما: این شرط بررسی می‌کند آیا «error» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(error)/* راهنما: این دستور عمداً یک خطا ایجاد می‌کند تا اجرای مسیر فعلی متوقف و کنترل خطا به لایه بالاتر منتقل شود. */ throw error;
  }else /* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:"Action ناشناخته است."},400)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:"Action ناشناخته است."},400);
  // راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json(await snapshot(admin,workspaceId))» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد.
  return json(await snapshot(admin,workspaceId));
 }catch(error:any){/* راهنما: این دستور یک عملیات اجرایی انجام می‌دهد: «console.error("booking-loyalty",error)». */ console.error("booking-loyalty",error);/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «json({ok:false,message:error?.message||"عملیات باشگاه مشتریان انجام نشد."}…» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return json({ok:false,message:error?.message||"عملیات باشگاه مشتریان انجام نشد."},400)}
});
// راهنما: این دستور از نوع ExportAssignment بخشی از کنترل جریان یا تعریف منطق این فایل است.
export default{async fetch(request:Request){/* راهنما: این شرط بررسی می‌کند آیا «request.method==="OPTIONS"» برقرار است؛ فقط در صورت درست بودن، شاخه مربوط اجرا می‌شود. */ if(request.method==="OPTIONS")/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «new Response("ok",{headers:corsHeaders})» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return new Response("ok",{headers:corsHeaders});/* راهنما: این Return اجرای تابع را در این نقطه تمام می‌کند و «handler(request)» را به فراخواننده برمی‌گرداند؛ در کامپوننت React می‌تواند UI خروجی باشد. */ return handler(request)}};
