import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server@1.4.1";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{...cors,"Cache-Control":"no-store"}});
async function membership(admin:any,userId:string){const{data,error}=await admin.from("WorkspaceMember").select("workspaceId,role").eq("userId",userId).limit(1);if(error)throw error;return data?.[0] as {workspaceId:string;role:string}|undefined;}
async function access(admin:any,workspaceId:string,userId:string){const{data,error}=await admin.from("BookingStaffAccess").select("isEnabled,permissions").eq("workspaceId",workspaceId).eq("userId",userId).maybeSingle();if(error)throw error;return data;}
function token(){const b=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function hash(v:string){const d=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));return [...d].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function snapshot(admin:any,workspaceId:string){
 const [responses,invites,appointments]=await Promise.all([
  admin.from("BookingFeedbackResponse").select("id,inviteId,appointmentId,customerId,rating,recommendScore,comment,tags,createdAt,BookingCustomer(fullName,phone),BookingAppointment(startsAt,BookingService(title),BookingStaff(name))").eq("workspaceId",workspaceId).order("createdAt",{ascending:false}).limit(300),
  admin.from("BookingFeedbackInvite").select("id,appointmentId,customerId,status,expiresAt,createdAt,updatedAt").eq("workspaceId",workspaceId).order("createdAt",{ascending:false}).limit(300),
  admin.from("BookingAppointment").select("id,startsAt,status,customerId,BookingCustomer(fullName,phone),BookingService(title),BookingStaff(name)").eq("workspaceId",workspaceId).in("status",["DONE","CONFIRMED"]).order("startsAt",{ascending:false}).limit(300),
 ]);const error=[responses.error,invites.error,appointments.error].find(Boolean);if(error)throw error;
 const rs=responses.data??[];const avg=rs.length?rs.reduce((s:number,x:any)=>s+Number(x.rating),0)/rs.length:0;const npsRows=rs.filter((x:any)=>x.recommendScore!=null);let nps:number|null=null;if(npsRows.length){const promoters=npsRows.filter((x:any)=>x.recommendScore>=9).length;const detractors=npsRows.filter((x:any)=>x.recommendScore<=6).length;nps=Math.round((promoters/npsRows.length-detractors/npsRows.length)*100);}
 return{ok:true,summary:{responses:rs.length,averageRating:Number(avg.toFixed(2)),nps},responses:rs,invites:invites.data??[],appointments:appointments.data??[]};
}
const handler=withSupabase({auth:"user"},async(req,ctx)=>{const userId=ctx.userClaims?.id;if(!userId)return json({ok:false,message:"ورود الزامی است."},401);const admin=ctx.supabaseAdmin;const m=await membership(admin,userId);if(!m)return json({ok:false,message:"Workspace پیدا نشد."},404);const adminRole=m.role==='ADMIN'||m.role==='SUPER_ADMIN';const a=adminRole?null:await access(admin,m.workspaceId,userId);if(!adminRole&&(!a?.isEnabled||a?.permissions?.customers!==true))return json({ok:false,message:"دسترسی رضایت‌سنجی ندارید."},403);
 if(req.method==='GET'){try{return json(await snapshot(admin,m.workspaceId));}catch(e){console.error(e);return json({ok:false,message:"اطلاعات رضایت‌سنجی در دسترس نیست."},500)}}if(req.method!=='POST')return json({ok:false,message:"Method not allowed"},405);
 let body:any;try{body=await req.json()}catch{return json({ok:false,message:"درخواست نامعتبر است."},400)}
 try{if(body.action==='create_invite'){const appointmentId=typeof body.appointmentId==='string'?body.appointmentId:'';const{data:appt,error}=await admin.from("BookingAppointment").select("id,status").eq("id",appointmentId).eq("workspaceId",m.workspaceId).maybeSingle();if(error)throw error;if(!appt)return json({ok:false,message:"نوبت پیدا نشد."},404);if(!['DONE','CONFIRMED'].includes(appt.status))return json({ok:false,message:"برای این وضعیت نوبت نمی‌توان رضایت‌سنجی ساخت."},400);const raw=token();const tokenHash=await hash(raw);const expiresAt=new Date(Date.now()+30*86400000).toISOString();const{error:ie}=await admin.from("BookingFeedbackInvite").upsert({workspaceId:m.workspaceId,appointmentId,customerId:'',tokenHash,status:'OPEN',expiresAt,createdByUserId:userId,updatedAt:new Date().toISOString()},{onConflict:"appointmentId"});if(ie)throw ie;return json({...await snapshot(admin,m.workspaceId),invite:{appointmentId,token:raw,path:`/feedback/${raw}`,expiresAt}},201);}if(body.action==='revoke_invite'){const id=typeof body.id==='string'?body.id:'';const{error}=await admin.from("BookingFeedbackInvite").update({status:'REVOKED',updatedAt:new Date().toISOString()}).eq("id",id).eq("workspaceId",m.workspaceId);if(error)throw error;return json(await snapshot(admin,m.workspaceId));}return json({ok:false,message:"عملیات شناخته‌شده نیست."},400);}catch(e){console.error('feedback-manage',e);return json({ok:false,message:"عملیات رضایت‌سنجی انجام نشد."},500)}});
export default{async fetch(req:Request){if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const r=await handler(req);const h=new Headers(r.headers);Object.entries(cors).forEach(([k,v])=>h.set(k,v));return new Response(r.body,{status:r.status,headers:h});}};
