import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server@1.4.1";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const actionTypes=new Set(["CATALOG","CART","ORDERS","SUPPORT","TEXT","URL","SUBMENU"]);
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:corsHeaders});
function cleanTitle(v:unknown){if(typeof v!=="string")return null;const x=v.trim();return x&&x.length<=64?x:null}
function cleanType(v:unknown){if(typeof v!=="string")return null;const x=v.trim().toUpperCase();return actionTypes.has(x)?x:null}
function cleanValue(type:string,v:unknown){if(v==null||v==="")return null;if(typeof v!=="string")throw new Error("invalid_value");const x=v.trim();if(type==="URL"){const u=new URL(x);if(!["http:","https:"].includes(u.protocol))throw new Error("invalid_url")}if(x.length>1500)throw new Error("invalid_value");return x}
async function workspaceForUser(admin:any,userId:string){const {data,error}=await admin.from("WorkspaceMember").select("workspaceId").eq("userId",userId).limit(1);if(error)throw error;return data?.[0]?.workspaceId as string|undefined}
async function ownedBot(admin:any,workspaceId:string,botId:string){const {data,error}=await admin.from("RubikaBot").select("id,rubikaBotId,username,displayName,description,status,welcomeMessage,createdAt").eq("id",botId).eq("workspaceId",workspaceId).maybeSingle();if(error)throw error;return data??null}
async function load(admin:any,workspaceId:string,botId?:string|null){const {data:bots,error}=await admin.from("RubikaBot").select("id,rubikaBotId,username,displayName,description,status,welcomeMessage,createdAt").eq("workspaceId",workspaceId).order("createdAt",{ascending:false});if(error)throw error;const bot=botId?(bots??[]).find((x:any)=>x.id===botId):(bots??[])[0];if(!bot)return{bots:bots??[],bot:null,buttons:[]};const {data:buttons,error:be}=await admin.from("RubikaButton").select("id,botId,parentId,title,actionType,actionValue,sortOrder,createdAt").eq("botId",bot.id).order("sortOrder");if(be)throw be;return{bots:bots??[],bot,buttons:buttons??[]}}
async function parent(admin:any,botId:string,v:unknown,self?:string){if(v==null||v==="")return null;if(typeof v!=="string"||v===self)throw new Error("invalid_parent");const {data}=await admin.from("RubikaButton").select("id").eq("id",v).eq("botId",botId).maybeSingle();if(!data)throw new Error("invalid_parent");return data.id}

const authenticated=withSupabase({auth:"user"},async(request,ctx)=>{const userId=ctx.userClaims?.id;if(!userId)return json({ok:false,message:"ورود به حساب الزامی است."},401);const admin=ctx.supabaseAdmin;let workspaceId:string|undefined;try{workspaceId=await workspaceForUser(admin,userId)}catch{return json({ok:false,message:"Workspace قابل دریافت نیست."},500)}if(!workspaceId)return json({ok:false,message:"Workspace پیدا نشد."},404);
if(request.method==="GET"){try{return json({ok:true,...await load(admin,workspaceId,new URL(request.url).searchParams.get("botId"))})}catch(e){console.error(e);return json({ok:false,message:"اطلاعات ربات روبیکا دریافت نشد."},500)}}
if(request.method!=="POST")return json({ok:false,message:"Method not allowed"},405);let body:Record<string,unknown>;try{body=await request.json()}catch{return json({ok:false,message:"درخواست معتبر نیست."},400)}const botId=typeof body.botId==="string"?body.botId:"";if(!botId)return json({ok:false,message:"ربات مشخص نشده است."},400);const bot=await ownedBot(admin,workspaceId,botId);if(!bot)return json({ok:false,message:"این ربات متعلق به Workspace شما نیست."},403);const action=typeof body.action==="string"?body.action:"";
try{if(action==="update_welcome"){if(typeof body.welcomeMessage!=="string")return json({ok:false,message:"پیام خوش‌آمد معتبر نیست."},400);const welcomeMessage=body.welcomeMessage.trim();if(!welcomeMessage||welcomeMessage.length>4000)return json({ok:false,message:"پیام خوش‌آمد باید بین ۱ تا ۴۰۰۰ کاراکتر باشد."},400);const {error}=await admin.from("RubikaBot").update({welcomeMessage,"updatedAt":new Date().toISOString()}).eq("id",bot.id);if(error)throw error}
else if(action==="create_button"){const title=cleanTitle(body.title),actionType=cleanType(body.actionType);if(!title||!actionType)return json({ok:false,message:"عنوان یا نوع دکمه معتبر نیست."},400);const parentId=await parent(admin,bot.id,body.parentId);const actionValue=cleanValue(actionType,body.actionValue);const {data:last}=await admin.from("RubikaButton").select("sortOrder").eq("botId",bot.id).eq("parentId",parentId).order("sortOrder",{ascending:false}).limit(1);const sortOrder=Number(last?.[0]?.sortOrder??0)+10;const {error}=await admin.from("RubikaButton").insert({id:crypto.randomUUID(),botId:bot.id,parentId,title,actionType,actionValue,sortOrder});if(error)throw error}
else if(action==="update_button"){const buttonId=typeof body.buttonId==="string"?body.buttonId:"";const {data:current}=await admin.from("RubikaButton").select("*").eq("id",buttonId).eq("botId",bot.id).maybeSingle();if(!current)return json({ok:false,message:"دکمه پیدا نشد."},404);const title=body.title===undefined?current.title:cleanTitle(body.title), actionType=body.actionType===undefined?current.actionType:cleanType(body.actionType);if(!title||!actionType)return json({ok:false,message:"عنوان یا نوع دکمه معتبر نیست."},400);const parentId=body.parentId===undefined?current.parentId:await parent(admin,bot.id,body.parentId,buttonId);const actionValue=body.actionValue===undefined?current.actionValue:cleanValue(actionType,body.actionValue);const {error}=await admin.from("RubikaButton").update({title,actionType,parentId,actionValue}).eq("id",buttonId).eq("botId",bot.id);if(error)throw error}
else if(action==="delete_button"){const buttonId=typeof body.buttonId==="string"?body.buttonId:"";await admin.from("RubikaButton").update({parentId:null}).eq("botId",bot.id).eq("parentId",buttonId);const {error}=await admin.from("RubikaButton").delete().eq("id",buttonId).eq("botId",bot.id);if(error)throw error}
else return json({ok:false,message:"عملیات پشتیبانی نمی‌شود."},400);return json({ok:true,...await load(admin,workspaceId,bot.id)})}catch(e){console.error(e);return json({ok:false,message:String(e).includes("invalid_parent")?"زیرمنوی انتخاب‌شده معتبر نیست.":String(e).includes("invalid_url")?"آدرس URL معتبر نیست.":"ذخیره تنظیمات روبیکا انجام نشد."},400)}});
export default{async fetch(request:Request){if(request.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});const r=await authenticated(request);const h=new Headers(r.headers);Object.entries(corsHeaders).forEach(([k,v])=>h.set(k,v));return new Response(r.body,{status:r.status,headers:h)}};
